### ISSUE TITLE
impacket包的版本是？

### ISSUE THREAD

**Issue by sevck** [r35tart/GetIPinfo#1]
```
python3 GetIPinfo.py
Traceback (most recent call last):
  File "GetIPinfo.py", line 20, in <module>
    from impacket.dcerpc.v5 import transport
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/impacket/dcerpc/v5/transport.py", line 141
    raise RuntimeError, 'virtual function'
```
环境：
mac 10.13.6
python 3.6
impacket (0.9.19)

**Comment by sevck** [comment]
impacket 0.9.21 is work
